In [1]:
import numpy as np
from scipy.special import comb

def gauss_quadrature_triangle(order):
    points, weights = np.polynomial.legendre.leggauss(order)
    num_points = len(points)
    quad_points = []
    quad_weights = []
    
    for i in range(num_points):
        for j in range(num_points - i):
            quad_points.append([points[i], points[j], points[num_points - i - j - 1]])
            quad_weights.append(weights[i] * weights[j] * weights[num_points - i - j - 1])
    
    return np.array(quad_points), np.array(quad_weights)

# Example usage
order = 3  # Change the order as needed
quad_points, quad_weights = gauss_quadrature_triangle(order)
print("Quadrature Points:")
print(quad_points)
print("Quadrature Weights:")
print(quad_weights)


Quadrature Points:
[[-0.77459667 -0.77459667  0.77459667]
 [-0.77459667  0.          0.        ]
 [-0.77459667  0.77459667 -0.77459667]
 [ 0.         -0.77459667  0.        ]
 [ 0.          0.         -0.77459667]
 [ 0.77459667 -0.77459667 -0.77459667]]
Quadrature Weights:
[0.17146776 0.43895748 0.17146776 0.43895748 0.43895748 0.17146776]
