In [1]:
import tensorflow as tf
print(tf.version)
import numpy as np

2023-09-23 22:56:07.744188: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-09-23 22:56:07.745485: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-09-23 22:56:07.779703: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-09-23 22:56:07.780147: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-09-23 22:56:08.463952: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Co

<module 'tensorflow._api.v2.version' from '/home/mariano/Documenti/test/base/lib/python3.9/site-packages/tensorflow/_api/v2/version/__init__.py'>


In [11]:
v=np.array([1.0,2.0,3.6])

print(tf.constant(v[:, np.newaxis], dtype=tf.float32))

tf.Tensor(
[[1. ]
 [2. ]
 [3.6]], shape=(3, 1), dtype=float32)


In [15]:
const_tensor = tf.constant([1, 2, 3])

modified_tensor=const_tensor+1


#you can do that but be carefull!!!!

In [17]:
scalar = tf.constant(10)
vector = tf.constant([1,2,3,4,5])
matrix = tf.constant([[1,2,3],[4,5,6]])
cube= tf.constant([[[1],
[2],[3]],[[4],[5],[6]],[[7],[8],[9]]])
print(scalar.get_shape())
print(vector.get_shape())
print(matrix.get_shape())
print(cube.get_shape())

()
(5,)
(2, 3)
(3, 3, 1)


In [18]:
#when you do operations with tf.const tf.var declare the function a @tf.function
#Since graphs can still be useful,@tf.function transparently converts Python functions into functions that are “backed” by graphs.Remember that @tf.function works best with TF 2 operations instead of NumPy opera-tions or Python primitives.
@tf.function
def calc_prod(x, y):
    z = 2*x + 3*y
    return z


x = tf.constant(5,name="x")
y = tf.constant(8,name="y")
result = calc_prod(x, y)
print('result =',result)

result = tf.Tensor(34, shape=(), dtype=int32)


In [25]:
a = tf.add(4, 2)
@tf.function
def compute_values():
    print(a) # 6
compute_values()

tf.Tensor(6, shape=(), dtype=int32)


In [27]:
@tf.function
def compute_values():
    a = tf.add(4, 2) #it doesn't compute the add opration it only holds types 
    print(a)
compute_values()

Tensor("Add:0", shape=(), dtype=int32)


In [28]:
@tf.function
def compute_values():
    a = tf.add(4, 2) #it doesn't compute the add opration it only holds types 
    tf.print(a)  # to print 
compute_values()

6


In [29]:
#or if you want the operation computed

def compute_values():
    a = tf.add(4, 2)
    return a  # to print 

print(compute_values())

tf.Tensor(6, shape=(), dtype=int32)


In [19]:
#initialize var to zero
var=tf.Variable(initial_value=tf.zeros(shape=(2,10),dtype=tf.float32))

print(var)

<tf.Variable 'Variable:0' shape=(2, 10) dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>


In [20]:
#you can convert tf.variable to a numpy array
v = tf.Variable([[1., 2., 3.], [4., 5., 6.]])
print("v.value():", v.value())
print("")
print("v.numpy():", v.numpy())
print("")

v.value(): tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)

v.numpy(): [[1. 2. 3.]
 [4. 5. 6.]]



In [23]:
A = tf.constant(3.0)
B = tf.constant([[2,3],[5.0,1.0]])
C = tf.constant([3.0, 4.0,6.0])

print('rank of A:',tf.rank(A),"shape of A:",tf.shape(A))
print('rank of B:',tf.rank(B),"shape of B:",tf.shape(B))
print('rank of C:',tf.rank(C),"shape of C:",tf.shape(C))



rank of A: tf.Tensor(0, shape=(), dtype=int32) shape of A: tf.Tensor([], shape=(0,), dtype=int32)
rank of B: tf.Tensor(2, shape=(), dtype=int32) shape of B: tf.Tensor([2 2], shape=(2,), dtype=int32)
rank of C: tf.Tensor(1, shape=(), dtype=int32) shape of C: tf.Tensor([3], shape=(1,), dtype=int32)


In [ ]:
#TF variables represent your model’s trainable parameters (e.g.,weights and biases of a neural network), whereas TF tensors represent thedata fed into your model and the intermediate representations of that data asit passes through your model.

In [40]:
@tf.function
def func():
    a = tf.constant([[10,10],[11.,1.]])
    b = tf.constant([[1.,0.],[0.,1.]])
    c = tf.matmul(a, b)
    return c
print(func().numpy())
#pointwise row moltiplication 


[[10. 10.]
 [11.  1.]]


In [42]:
def func():
    a = tf.constant([[10,10],[11.,1.]])
    b = tf.constant([[1.,0.],[0.,1.]])
    c = tf.matmul(a, b)
    return c
print(func().numpy())

[[10. 10.]
 [11.  1.]]


In [43]:
print(tf.autograph.to_code(func)) #to see the aoutograph generated by a function works only with not #tf.functions

def tf__func():
    with ag__.FunctionScope('func', 'fscope', ag__.ConversionOptions(recursive=True, user_requested=True, optional_features=(), internal_convert_user_code=True)) as fscope:
        do_return = False
        retval_ = ag__.UndefinedReturnValue()
        a = ag__.converted_call(ag__.ld(tf).constant, ([[10, 10], [11.0, 1.0]],), None, fscope)
        b = ag__.converted_call(ag__.ld(tf).constant, ([[1.0, 0.0], [0.0, 1.0]],), None, fscope)
        c = ag__.converted_call(ag__.ld(tf).matmul, (ag__.ld(a), ag__.ld(b)), None, fscope)
        try:
            do_return = True
            retval_ = ag__.ld(c)
        except:
            do_return = False
            raise
        return fscope.ret(retval_, do_return)



In [47]:
v1 = tf.Variable([4.0, 4.0])
c1 = tf.constant([1.0, 2.0])
diff = tf.subtract(v1,c1)
print("diff:",diff)

v1=v1+1

print("diff:",diff)

#is like you would expect

diff: tf.Tensor([3. 2.], shape=(2,), dtype=float32)
diff: tf.Tensor([3. 2.], shape=(2,), dtype=float32)


In [60]:
#operation of tensors

x = tf.constant([[1., 2., 3.], [4., 5., 6.]])
print("x:", x)
print("")
print("x.shape:", x.shape)
print("")
print("x.dtype:", x.dtype)
print("")
print("x[:, 1:]:", x[:, 1:])
print("")
print("x[..., 1, tf.newaxis]:", x[..., 1, tf.newaxis])
print("")
print("x[1]:", x[1])
print("")
print("x + 10:", x + 10)
print("")
print("tf.square(x):", tf.square(x))
print("")
print("x @ tf.transpose(x):", x @ tf.transpose(x)) #for standard matrix vec mult


x: tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)

x.shape: (2, 3)

x.dtype: <dtype: 'float32'>

x[:, 1:]: tf.Tensor(
[[2. 3.]
 [5. 6.]], shape=(2, 2), dtype=float32)

x[..., 1, tf.newaxis]: tf.Tensor(
[[2.]
 [5.]], shape=(2, 1), dtype=float32)

x[1]: tf.Tensor([4. 5. 6.], shape=(3,), dtype=float32)

x + 10: tf.Tensor(
[[11. 12. 13.]
 [14. 15. 16.]], shape=(2, 3), dtype=float32)

tf.square(x): tf.Tensor(
[[ 1.  4.  9.]
 [16. 25. 36.]], shape=(2, 3), dtype=float32)

x @ tf.transpose(x): tf.Tensor(
[[14. 32.]
 [32. 77.]], shape=(2, 2), dtype=float32)


In [55]:
m1 = tf.constant([[1., 2., 4.], [3., 6., 12.]])
print("m1:", m1)
print("m1 + 50:", m1 + 50)
print("m1 * 2:", m1 * 2)
print("tf.square(m1):", tf.square(m1))

m1: tf.Tensor(
[[ 1.  2.  4.]
 [ 3.  6. 12.]], shape=(2, 3), dtype=float32)
m1 + 50: tf.Tensor(
[[51. 52. 54.]
 [53. 56. 62.]], shape=(2, 3), dtype=float32)
m1 * 2: tf.Tensor(
[[ 2.  4.  8.]
 [ 6. 12. 24.]], shape=(2, 3), dtype=float32)
tf.square(m1): tf.Tensor(
[[  1.   4.  16.]
 [  9.  36. 144.]], shape=(2, 3), dtype=float32)


In [61]:
def call():
    return x*x*w*w

In [68]:
x=tf.Variable(1,dtype=tf.float32)
w=tf.Variable(3,dtype=tf.float32)

d=tf.constant(0,dtype=tf.float32)
with tf.GradientTape() as tape:
    #tape.watch(w)  #the same is you have proper variables

    for i in range(2):
        with tf.GradientTape() as tape_:
            tape_.watch(x)
            z=call()
        d+=tape_.gradient(z,x)
res=tape.gradient(d,w)

print(d)
print(res)

tf.Tensor(36.0, shape=(), dtype=float32)
tf.Tensor(24.0, shape=(), dtype=float32)


In [72]:
x = tf.ones((3, 3))
print(x)
print()
with tf.GradientTape() as t:
    t.watch(x)
    y = tf.reduce_sum(x)
    print("y:",y)
    z = tf.multiply(y, y)
    print("z:",z)
    z = tf.multiply(z, y)
    print("z:",z)
# the derivative of z with respect to y
dz_dy = t.gradient(z, y)
print("dz_dy:",dz_dy)


tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)

y: tf.Tensor(9.0, shape=(), dtype=float32)
z: tf.Tensor(81.0, shape=(), dtype=float32)
z: tf.Tensor(729.0, shape=(), dtype=float32)
dz_dy: tf.Tensor(243.0, shape=(), dtype=float32)


In [ ]:
a=tf.constant([[1,2],[3,4]])
x=tf.constant([[1,2]])

print(a)
print(x)